import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { Injectable, Logger } from '@nestjs/common';
import { createReadStream } from 'node:fs';
import { mkdir, rename, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import type { Readable } from 'node:stream';
import { environment } from '../config/environment.js';

/** File types tenants' documents may be uploaded as. SVG and HTML are excluded: they can carry script. */
export const UPLOAD_TYPES = {
  'application/pdf': 'pdf',
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
} as const;
export type UploadType = keyof typeof UPLOAD_TYPES;

export function isUploadType(value: string): value is UploadType {
  return Object.hasOwn(UPLOAD_TYPES, value);
}

/** Identifies a file from its first bytes. The declared Content-Type is never trusted on its own. */
export function sniffType(bytes: Uint8Array): UploadType | null {
  const starts = (signature: number[], offset = 0) => signature.every((byte, i) => bytes[offset + i] === byte);
  if (starts([0x25, 0x50, 0x44, 0x46, 0x2d])) return 'application/pdf'; // %PDF-
  if (starts([0xff, 0xd8, 0xff])) return 'image/jpeg';
  if (starts([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) return 'image/png';
  if (starts([0x52, 0x49, 0x46, 0x46]) && starts([0x57, 0x45, 0x42, 0x50], 8)) return 'image/webp'; // RIFF....WEBP
  return null;
}

export interface StoredFile {
  body: Readable;
  size?: number;
}

interface Driver {
  put(key: string, body: Buffer, contentType: UploadType): Promise<void>;
  get(key: string): Promise<StoredFile | null>;
  delete(key: string): Promise<void>;
}

/** Keys are generated by the server (`<organizationId>/<uuid>.<ext>`) and validated again before any I/O. */
const KEY_PATTERN = /^[0-9a-f-]{36}\/[0-9a-f-]{36}\.(pdf|jpg|png|webp)$/;

function assertKey(key: string): void {
  if (!KEY_PATTERN.test(key)) throw new Error('Invalid storage key');
}

class LocalDriver implements Driver {
  private readonly root = resolve(environment().STORAGE_DIR);

  private path(key: string): string {
    const path = resolve(this.root, key);
    if (!path.startsWith(this.root + sep)) throw new Error('Invalid storage key');
    return path;
  }

  async put(key: string, body: Buffer): Promise<void> {
    const path = this.path(key);
    await mkdir(dirname(path), { recursive: true, mode: 0o700 });
    // Write then rename so a crash never leaves a half-written file under the final name.
    const temporary = `${path}.partial`;
    await writeFile(temporary, body, { mode: 0o600, flag: 'wx' });
    await rename(temporary, path);
  }

  async get(key: string): Promise<StoredFile | null> {
    const path = this.path(key);
    try {
      const info = await stat(path);
      return { body: createReadStream(path), size: info.size };
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw error;
    }
  }

  async delete(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }
}

class S3Driver implements Driver {
  private readonly env = environment();
  private readonly client = new S3Client({
    region: this.env.S3_REGION,
    endpoint: this.env.S3_ENDPOINT || undefined,
    forcePathStyle: this.env.S3_FORCE_PATH_STYLE,
    credentials: { accessKeyId: this.env.S3_ACCESS_KEY_ID, secretAccessKey: this.env.S3_SECRET_ACCESS_KEY },
  });

  async put(key: string, body: Buffer, contentType: UploadType): Promise<void> {
    await this.client.send(
      new PutObjectCommand({
        Bucket: this.env.S3_BUCKET,
        Key: key,
        Body: body,
        ContentType: contentType,
        ContentLength: body.length,
        ServerSideEncryption: this.env.S3_ENDPOINT ? undefined : 'AES256',
      }),
    );
  }

  async get(key: string): Promise<StoredFile | null> {
    try {
      const result = await this.client.send(new GetObjectCommand({ Bucket: this.env.S3_BUCKET, Key: key }));
      if (!result.Body) return null;
      return { body: result.Body as Readable, size: result.ContentLength };
    } catch (error) {
      if ((error as { name?: string }).name === 'NoSuchKey') return null;
      throw error;
    }
  }

  async delete(key: string): Promise<void> {
    await this.client.send(new DeleteObjectCommand({ Bucket: this.env.S3_BUCKET, Key: key }));
  }
}

/**
 * Private storage for uploaded documents. Files are only ever served through the
 * API after an organization-scoped authorization check; the bucket or directory
 * must never be public.
 */
@Injectable()
export class FileStore {
  private readonly logger = new Logger(FileStore.name);
  private driver?: Driver;

  private get active(): Driver {
    this.driver ??= environment().STORAGE_DRIVER === 's3' ? new S3Driver() : new LocalDriver();
    return this.driver;
  }

  static keyFor(organizationId: string, id: string, type: UploadType): string {
    return `${organizationId}/${id}.${UPLOAD_TYPES[type]}`;
  }

  async put(key: string, body: Buffer, type: UploadType): Promise<void> {
    assertKey(key);
    await this.active.put(key, body, type);
  }

  async get(key: string): Promise<StoredFile | null> {
    assertKey(key);
    return this.active.get(key);
  }

  /** Best effort: a failure is logged for follow-up, never surfaced to the user. */
  async delete(key: string): Promise<void> {
    try {
      assertKey(key);
      await this.active.delete(key);
    } catch (error) {
      this.logger.error(`STORAGE_DELETE_FAILED key=${key} ${(error as Error).name}`);
    }
  }
}
